---
server:
  port: 8080
  contextPath: /SpringBootDemoApp
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:sqlserver://localhost;databaseName=ForexDB;integratedSecurity=true
    username: 
    password: 
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.SQLServer2008Dialect

